import React,{useEffect,useState} from 'react';

async function request(path='',options){const r=await fetch('/api/v1/cases'+path,options);const d=await r.json();if(!r.ok)throw Error(d.detail||'Không tải được lịch sử');return d;}
export default function CaseHistory({refreshKey}){
 const [items,setItems]=useState([]),[selected,setSelected]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const data=await request();setItems(data.items)}catch(e){setMessage(e.message)}}
 useEffect(()=>{load()},[refreshKey]);
 async function save(){setBusy(true);try{await request('/'+selected.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:selected.status,note:selected.note})});setMessage('Đã lưu đánh giá');await load()}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 async function remove(){if(!window.confirm('Xóa case này và ảnh đã lưu?'))return;setBusy(true);try{await request('/'+selected.id,{method:'DELETE'});setSelected(null);await load();setMessage('Đã xóa case và ảnh')}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 return <section className="card" style={{marginTop:20}}><h2>Lịch sử kiểm tra · {items.length}/100</h2><p className="muted">Giữ 100 case mới nhất. Case cũ nhất và ảnh tự động bị xóa khi vượt giới hạn.</p><button onClick={load}>Làm mới lịch sử</button>{message&&<p role="status">{message}</p>}<div className="grid">{items.map(c=><button key={c.id} className="person card" onClick={()=>{setSelected({...c});setMessage('')}}><img src={'/api/v1/cases/'+c.id+'/image'} loading="lazy" alt="Ảnh case"/><div><strong>{new Date(c.created_at).toLocaleString('vi-VN')}</strong><p>{c.result.total_faces} khuôn mặt · {c.result.elapsed_ms} ms</p><small>{({unreviewed:'Chưa xem',correct:'Đúng',needs_fix:'Cần sửa'})[c.status]}</small><code>{c.id.slice(0,8)}</code></div></button>)}</div>{selected&&<section style={{marginTop:24}}><h2>Chi tiết case {selected.id.slice(0,8)}</h2><div style={{position:'relative',maxWidth:720,margin:'auto'}}><img style={{width:'100%',display:'block'}} src={'/api/v1/cases/'+selected.id+'/image'} alt="Ảnh đã lưu"/>{selected.result.faces.map((f,i)=><div key={i} style={{position:'absolute',border:'2px solid var(--primary)',left:100*f.box[0]/selected.result.width+'%',top:100*f.box[1]/selected.result.height+'%',width:100*f.box[2]/selected.result.width+'%',height:100*f.box[3]/selected.result.height+'%'}}/>)}</div><label className="field">Đánh giá<select value={selected.status} onChange={e=>setSelected({...selected,status:e.target.value})}><option value="unreviewed">Chưa xem</option><option value="correct">Đúng</option><option value="needs_fix">Cần sửa</option></select></label><label className="field">Ghi chú<textarea style={{width:'100%',minHeight:90,border:'1px solid var(--border)',padding:12}} maxLength={4000} value={selected.note} onChange={e=>setSelected({...selected,note:e.target.value})}/></label><div className="camera-actions"><button className="primary" disabled={busy} onClick={save}>Lưu đánh giá</button><button disabled={busy} onClick={remove}>Xóa case và ảnh</button><button onClick={()=>setSelected(null)}>Đóng chi tiết</button></div><details><summary>Kết quả gốc và phiên bản xử lý</summary><pre>{JSON.stringify(selected.result,null,2)}</pre></details></section>}</section>
}
